# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # https://app.vagrantup.com/hashicorp/boxes/bionic64
    config.vm.box = "hashicorp/bionic64"
    
  
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    config.vm.network "private_network", ip: "192.168.56.30"
  
    # Share an additional folder to the guest VM
    # config.vm.synced_folder "./shared", "/vagrant_data"
  
    # Customize the disk size on the guest VM: (using vagrant-disksize plugin)
    # config.disksize.size = '15GB' 
  
    # Customize hostname of the guestVM 
    config.vm.hostname = "rancher-server"
  
    config.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the guest VM:
      vb.memory = "4096"
      vb.cpus = 2
    end
  
    # Enable provisioning guest VM with shell script
    config.vm.provision "shell", path: "./provision/default_provision.sh"
    config.vm.provision "shell", path: "./provision/dev_provision.sh", privileged: false
  
  end